title: <p align="center"> Luis Gustavo Anzola Simancas </p>

logo: "cv/Luis Anzola.png"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/luis-gustavo-anzola-simancas-075756157/">LinkedIn</a> |
  <a href="cv/Curriculum Vitae Luis G Anzola.pdf">Curriculum</a>
  </p>
  
  <p align="center">
  <img src="https://readme-typing-svg.herokuapp.com?font=Lato&weight=700&size=22&pause=1000&color=500000&center=true&vCenter=true&width=450&lines=Hi+Everyone!+%F0%9F%91%8B;Welcome+to+my+portfolio+website!" alt="Typing SVG" />
  <br />
  📌 Civil Ingenier <i>Universidad Nacional Experimental Francisco de Miranda</i>
  <br />
  📌 Photographer <i>AC Milan</i>
  </p>
  
theme: jekyll-theme-minimal

